spring.application.name=ContentSummarizer
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Static Resources
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.chain.enabled=true

# Allow CORS for your frontend
server.servlet.register-default-servlet=true

groq.api.url = https://api.groq.com/openai/v1/chat/completions
groq.api.key = ${GROQ.API.KEY}
